sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/rdhyee/gitberg.git
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+git://github.com/rdhyee/pg-epubmaker.git
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Zm5mf2XKf56rV36Nqh06FQBkNzPae0cfGElrrAJYorwqKxh5eASfJ8fMAfTAzO9jT1NF1guFqshnxahQlpvTFXmV9B5/BnM2n49GOZcLQZdvifjrPxBNsenGMb1tbnKUkA8YbSDp6Qw2Vmh2tK3/ALuZtzdaql+otFCXf+36l6SKFh2YRphlv8/GpJz2U6cN4FLILBJVfo7r9+btt0Zarz+WCA3F/RfJKBJbYBNgkgmRlu9Nb3UfLTrbrzkgq6+mwfBfkQofD8fyQw7PLXON9TSEUKmzUyZSTLR3fH/lZWio/0Wqxm7T1Mv3N9wnphSu6N5Q+imnX9Fx8y+S2m4fjlnYU1snaQYN3zN5qf4wpkeHBaiZSq/Nlt8xBGavhexoSdBHIB92K8EVfwffKzAG2O72dAjeSilJInSyfhun0zPBK2cSZ1CWUG2+4bq7yXaC183npHZm/g4HcgOZ1OI2T6mpTDwoxkej6qVw8cxJ+7wuOTWiTo4cjtIMCswjthkKPKbGstaxFKlC3BrHPunkKWSfRt4P7iIylEK/Q542zDkllQ3NVYxtiJPNBMQk6n4QR9t3kyWLtyp1lB6I/aimfuR0YnzCmjZODCokxgQggGYozZYxvU8oZ3b2lz/SyiGFIQgBYGh59pwIS/pCq1qPQ1ulPD+9De6YX4eTSs0qkZE=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: rdhyee/Tess-of-the-d-Urbervilles--a-Pure-Woman_110
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy